[package]
name = "wow_srp"
description = "Server and client library for the World of Warcraft flavor of SRP6 with support for reconnection."
license = "MIT OR Apache-2.0"
repository = "https://www.github.com/gtker/wow_srp"
keywords = ["wow", "world-of-warcraft", "srp6", "authentication", "login"]
categories = ["authentication", "cryptography", "game-development", "game-engines"]
readme = "README.md"
version = "0.2.0" # Remember to update html_root_url in src/lib.rs
authors = ["Gtker <github@gtker.com"]
edition = "2018"

[dependencies]
sha-1 = "0.9"
num-bigint = "0.4"
hex = "0.4"
rand = "0.8"

[dev-dependencies]
hex-literal = "0.3"
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
