[package]
name = "wow_srp"
description = "Server and client library for the World of Warcraft flavor of SRP6 with support for reconnection."
license = "MIT OR Apache-2.0"
repository = "https://www.github.com/gtker/wow_srp"
keywords = ["wow", "world-of-warcraft", "srp6", "authentication", "login"]
categories = ["authentication", "cryptography", "game-development", "game-engines"]
readme = "README.md"
version = "0.3.0" # Remember to update html_root_url and docs in src/lib.rs, and README.md
authors = ["Gtker <github@gtker.com"]
edition = "2018"

[features]
default = ["default-math"]
default-math = ["num-bigint"]
fast-math = ["rug"]

[dependencies]
# Required for SRP6 algorithm
sha-1 = "0.9"

# Required for generating private keys
rand = "0.8"

# Required for SRP6 algorithm.
# rug is ~100% faster than num-bigint (50% reduced time used) but is not
# pure Rust so it has external dependencies.
num-bigint = { version = "0.4", optional = true }
rug = { version = "1.13", features = ["integer"], default-features = false, optional = true }

[dev-dependencies]
# Used only in doctest to show easily readable large safe prime
hex-literal = "0.3"
# Used for easily converting hex strings to arrays for tests
hex = "0.4"
# Required for benchmarking.
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
